version: '3.8'

services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=Asia/Tokyo
    volumes:
      - ./src:/var/www
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - 5173:5173
    working_dir: /var/www
    environment:
      - TZ=Asia/Tokyo